dist: xenial
sudo: required
language: java
os: linux
jdk:
- openjdk18
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
before_script:
  - sh -e /etc/init.d/xvfb start
before_install:
  - chmod +x mvnw
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
# script:
#    - export JAVA_HOME=$HOME/openjdk18
